import React, { useState } from 'react';
import { FaPlus, FaMinus } from 'react-icons/fa';

const faqData = [
    {
        question: "How Does Aniuqest work?",
        answer: "Aniquest uses AI to generate high-quality content based on user prompts."
    },
    {
        question: "What texts can you generate with Aniuqest?",
        answer: "From blog posts and essays to marketing copy and summaries."
    },
    {
        question: "How does the Aniuqest AI work?",
        answer: "It’s powered by a language model trained on diverse content to provide relevant outputs."
    },
    {
        question: "Can I try Aniuqest for free?",
        answer: "Yes, you can access a free trial with limited features."
    },
    {
        question: "Can the AI write stories or posts of +1000 words?",
        answer: "Of course, our AI is trained to develop long texts, but we strongly recommend being as objective and specific with your definitions in order to get a perfect job."
    },
    {
        question: "Is the content generated by Aniuqest AI original?",
        answer: "Yes, it generates original content every time."
    },
    {
        question: "How can I make the AI check my texts?",
        answer: "You can paste your text and use the grammar check feature built into Aniuqest."
    }
];

const FAQ = () => {
    const [activeIndex, setActiveIndex] = useState(null);

    const toggle = (index) => {
        setActiveIndex(prevIndex => (prevIndex === index ? null : index));
    };

    return (
        <div className="w-full md:max-w-[80%] mx-auto pb-10 pt-15 sm:pt-30">
                <h2 className="text-xl xs:text-3xl md:text-5xl font-bold text-center w-[80%] lg:w-[60%] xl:w-1/2 mx-auto mb-6 md:leading-[60px]">Frequently Asked Questions</h2>
            <div className="space-y-4">
                {faqData.map((item, index) => (
                    <div
                        key={index}
                        className="bg-white rounded-lg shadow-sm"
                    >
                        <button
                            className="w-full flex justify-between items-center pl-4 pr-2 py-4 text-left focus:outline-none"
                            onClick={() => toggle(index)}
                        >
                            <span className="text-[10px] xs:text-sm sm:text-xl font-semibold text-gray-800">{item.question}</span>
                            <div className='w-8 sm:w-12 h-8 sm:h-12 bg-[#F8E4F9] flex items-center justify-center rounded-sm'>
                                <span className="text-[#9638C5] font-bold text-xl sm:text-3xl cursor-pointer">
                                {activeIndex === index ? "-" : "+"}
                            </span>
                            </div>
                        </button>
                        {activeIndex === index && (
                            <div className="px-4 pb-4 text-gray-600 text-[12px] sm:text-base">
                                {item.answer}
                            </div>
                        )}
                    </div>
                ))}
            </div>
        </div>
    );
};

export default FAQ;
